### YamlMime:ManagedReference

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  # Specify .NET version compatible with DocFx if needed
      installationPath: $(Agent.ToolsDirectory)/dotnet
  
  - script: |
      echo "Installing DocFx..."
      dotnet tool install -g docfx 
    displayName: 'Install DocFx'

  - script: |
      echo "Building DocFx documentation..."
      export PATH="$PATH:~/.dotnet/tools"
      docfx build -t statictoc
    displayName: 'Build DocFx site'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Pipeline.Workspace)/s/_site'  # Path to the generated site
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'  # Define the zip file location
      replaceExistingArchive: true
    displayName: 'Archive _site as ZIP'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Microsoft Azure-sponsorat (272471bb-b3f1-4888-9177-bba5860f7173)'
      appType: 'webApp'
      WebAppName: 'channelcrmdocfx'
      package: '$(Build.ArtifactStagingDirectory)/site.zip'
      

