# Starter pipeline for building and deploying DocFx documentation site

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Specify .NET version compatible with DocFx if needed
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NodeTool@0
    inputs:
      versionSpec: '21.x'  # Node.js is needed for Azure Static Web Apps CLI

  - script: |
      echo "Installing DocFx..."
      dotnet tool install -g docfx 
    displayName: 'Install DocFx'

  - script: |
      echo "Building DocFx documentation..."
      export PATH="$PATH:~/.dotnet/tools"
      docfx build
    displayName: 'Build DocFx site'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Microsoft Azure-sponsorat (272471bb-b3f1-4888-9177-bba5860f7173)'
      appType: 'webAppLinux'
      WebAppName: 'channelcrmdocs'
      packageForLinux: '$(System.DefaultWorkingDirectory)/_site/*.*'
      RuntimeStack: 'NODE|18-lts'
