# Starter pipeline for building and deploying DocFx documentation site

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Specify .NET version compatible with DocFx if needed
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # Node.js is needed for Azure Static Web Apps CLI

  - script: |
      echo "Installing DocFx..."
      dotnet tool install -g docfx 
    displayName: 'Install DocFx'

  - script: |
      echo "Run DocFx..."
      docfx docfx.json
    displayName: 'Run DocFx'

  - script: |
      echo "Building DocFx documentation..."
      export PATH="$PATH:~/.dotnet/tools"
      docfx build
    displayName: 'Build DocFx site'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Pipeline.Workspace)/s/_site'  # Path to the generated site
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/site.zip'  # Define the zip file location
      replaceExistingArchive: true
    displayName: 'Archive _site as ZIP'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Microsoft Azure-sponsorat (272471bb-b3f1-4888-9177-bba5860f7173)'
      appType: 'webAppLinux'
      appName: 'channelcrmdocs2'
      package: '$(Build.ArtifactStagingDirectory)/site.zip'
      runtimeStack: 'DOTNETCORE|6.0'